---
- name: Ansible Install
  hosts: auto.loudwalrus.com
  vars:
    ansible_connection: ssh # ansible-core won't handle local properly
  become: true
  run_once: true
  gather_facts: true

  tasks:

    - name: Copy and extract AAP installer
      ansible.builtin.unarchive:
        src: /mnt/loop/ansible/satellite/ansible-automation-platform-containerized-setup-2.6-1.tar.gz
        creates: /home/ansible/ansible-automation-platform-containerized-setup-2.6-1
        remote_src: true
        dest: /home/ansible
        owner: ansible
        group: ansible
        mode: '0744'
    - name: Copy inventory file # TODO: template this a bit
      ansible.builtin.copy:
        src: /mnt/loop/ansible/satellite/inventory-growth-custom
        remote_src: true
        dest: /home/ansible/ansible-automation-platform-containerized-setup-2.6-1/inventory
        owner: ansible
        group: ansible
        mode: '0644'
        backup: true

# TODO: Unsure if I need to do this step :
#  https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/containerized_installation/advanced-configuration-containerized#proc-add-eda-safe-plugin-var
# TODO: Perhaps I should set up the postgres externally, but not yet
# TODO: Also, I should setup certs someday

    - name: Run containerized install
      ansible.builtin.command:
        chdir: /home/ansible/ansible-automation-platform-containerized-setup-2.6-1
        argv:
          - ansible-playbook
          - -i
          - inventory
          - ansible.containerized_installer.install
      become: true # TODO: is this needed?
      become_user: ansible
      changed_when: true
