# Intent is to put things in this playbook that should/must be run before authentication
# is properly setup.
#
# While everything is idempotent here, nothing here should require being re-run, even
# if there are problems with the installation. Effectively this is a continuation of
# bootstrapping. We check prerequisites and do some basic RHEL config.
#

- name: Ansible Preflight Checks
  hosts: localhost # We don't have DNS yet
  vars:
    ansible_connection: local
    aap_hostname: 'ansible27.loudwalrus.com'
    key_src_dir: "/mnt/sync/ansible/ssh_keys"
    target_users:
      - ogren
      - ansible
  become: true
  run_once: true
  gather_facts: true
  tasks:

    ## Requirements validation
    - name: RHEL version Check
      ansible.builtin.fail:
      when: ansible_distribution != "RedHat" or ansible_distribution_major_version != "9"
    - name: Check for a minimum of 4 CPU
      ansible.builtin.fail:
      when: ansible_processor_vcpus < 4
    - name: Debug memory
      ansible.builtin.debug:
        var: ansible_memtotal_mb
    - name: Check for minimum memory
      ansible.builtin.fail:
      when: ansible_memtotal_mb < 15500 # Found 15700 on a 16GB system so I give some leeway, 16384 would be true 16GB
    - name: Get free space in /var
      ansible.builtin.shell:
        cmd: 'set -o pipefail && df -B1 --output=avail / | tail -1'
      register: var_free
      changed_when: false
    - name: Check for a minimum of 60 GB in / )
      ansible.builtin.fail:
      when: var_free.stdout | int < 60 * 1024 * 1024 * 1024

    ## Prep for using ssh
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ aap_hostname }}"
        
    ## Other Config
    - name: Add Ansible user
      ansible.builtin.user:
        state: present
        name: ansible
        password_lock: true
        generate_ssh_key: false

    - name: Add ansible user to sudoers
      ansible.builtin.lineinfile:
        state: present
        path: /etc/sudoers
        line: "{{ item }} ALL=(ALL:ALL) NOPASSWD:ALL"
        insertafter: '%wheel	ALL=(ALL)	ALL'
        validate: 'visudo -cf %s'
      loop: "{{ target_users }}"        

    - name: Ensure .ssh directory exists for users
      ansible.builtin.file:
        path: "/home/{{ item }}/.ssh"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0700'
      loop: "{{ target_users }}"        
  
    - name: Copy authorized_keys
      ansible.builtin.copy:
        src: "{{ key_src_dir }}/authorized_keys"
        dest: "/home/{{ item }}/.ssh"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0600'
      loop: "{{ target_users }}"      

#   This config will specify our non default SSH keys for the local servers
#   Note that since these are still going to be CLI playbooks we can't use templates
    - name: Copy config
      ansible.builtin.copy:
        src: "{{ key_src_dir }}/config"
        dest: "/home/{{ item }}/.ssh"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0600'
      loop: "{{ target_users }}"      

    - name: Copy secret key
      ansible.builtin.copy:
        src: "{{ key_src_dir }}/id_ogren_homelab"
        dest: "/home/{{ item }}/.ssh"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0600'
      loop: "{{ target_users }}"      
        

