# Intent is to put things in this playbook that should be run before every install
# attempt (but not the install)
#
# Because we are updating content this may reboot
#
# Remember that because this forces ssh and we don't have inventory we must provide
# it to ansible-playbook (and use a trailing comma so that it knows it's not a file)
#
# ansible-playbook --check -i "ansible27.loudwalrus.com," ~/personal-aap/misc/ansible-002-prep.yml 

---
- name: Ansible Final System Prep
  hosts: ansible27.loudwalrus.com
  vars:
    ansible_connection: ssh # ansible-core won't handle local properly
  become: true
  run_once: true
  gather_facts: true

  tasks:

## Content
    - name: Add Standard content
      ansible.builtin.dnf:
        name: "ansible-core,git-core,sysstat,kpatch"
        state: present

    - name: Ensure kpatch systemd service is enabled and started
      ansible.builtin.systemd:
        name: kpatch
        enabled: true
        state: started

    - name: Install latest cumulative kpatch package for running kernel
      ansible.builtin.dnf:
        name: "kpatch-patch-{{ ansible_kernel | regex_replace('\\.', '_') | regex_replace('-', '_') }}"
        state: latest
      ignore_errors: true  # Prevents failure if no live patch currently exists for this kernel

    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
        

 ## Reboot if needed       
    - name: Check to see if we need a reboot
      ansible.builtin.command: needs-restarting -r
      become: true
      register: needrestart_result
      failed_when: false # non-zero return just indicates reboot is needed
      changed_when: false

    - name: Reboot Server if Necessary
      ansible.builtin.reboot:
        msg: Ansible forcing reboot
        pre_reboot_delay: 3
      become: true
      when: needrestart_result.rc == 1
