# Intent is to put things in this playbook that should be run before every install
# attempt (but not the install)
#
# Because we are updating content this may reboot
#
# Remember that because this forces ssh and we don't have inventory we must provide
# it to ansible-playbook (and use a trailing comma so that it knows it's not a file)
#
# ansible-playbook --check -i "ansible27.loudwalrus.com," ~/personal-aap/misc/ansible-002-prep.yml 

---
- name: Ansible Final System Prep
  hosts: ansible27.loudwalrus.com
  vars:
    ansible_connection: ssh # ansible-core won't handle local properly
    kernel_settings_sysctl:
      - name: vm.swappiness
        value: 75 # This going to be a memory constrained system
  become: true
  run_once: true
  gather_facts: true

  tasks:

## Content
    - name: Add Standard content
      ansible.builtin.dnf:
        name: "ansible-core,git-core,sysstat,kpatch,kpatch-dnf,rhel-system-roles"
        state: present

    - name: Add Ansible Builder
      ansible.builtin.dnf:
        name: "ansible-builder"
        enablerepo: ansible-automation-platform-2.7-for-rhel-9-x86_64-rpms
        state: present

    - name: Ensure kpatch systemd service is enabled and started
      ansible.builtin.systemd:
        name: kpatch
        enabled: true
        state: started

    - name: Enable package filtering to restrict updates to kpatch-supported kernels
      ansible.builtin.command:
        cmd: dnf kpatch auto-filter
      register: kpatch_filter
      changed_when: "'enabled' in kpatch_filter.stdout"

    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
 
    - name: Enable automatic subscription to kernel live patch streams
      ansible.builtin.command:
        cmd: dnf kpatch auto
      register: kpatch_auto
      changed_when: not "'Nothing' in kpatch_auto.stdout"

    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true

    - name: Apply kernel settings
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.kernel_settings
        
 ## Reboot if needed       
    - name: Check to see if we need a reboot
      ansible.builtin.command: "dnf needs-restarting -r"
      become: true
      register: needrestart_result
      failed_when: false # non-zero return just indicates reboot is needed
      changed_when: false

    - name: Reboot Server if Necessary
      ansible.builtin.reboot:
        msg: Ansible forcing reboot
        pre_reboot_delay: 3
      become: true
      when: needrestart_result.rc == 1

