# Designed for drift prevention on Ansible Controllers
# Unlike other similar playbooks, does not actually install AAP: too much recursive behavior down that road. 
# 
# Requires Loop SMB Credential

---
- name: Configure Ansible Host
  hosts: ansiblehosts
  gather_facts: false
  vars:
    run: false
    reboot: false

  # Primarily just doing this as an example of a secondary credential
  tasks:
    - name: Add Ansible content
      ansible.builtin.dnf:
        name: "{{ ansible_content }}"
        enablerepo: ansible-automation-platform-2.4-for-rhel-8-x86_64-rpms
        state: present #Will update in next step if necessary
      become: true
      register: dnf_ansible_taskout

    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
      become: true  
      register: dnf_update_taskout

    - name: Load passwd as database so that we can extract rheluser uid and group
      ansible.builtin.getent:
        database: passwd

    - name: Log uid since mount task will be redacted
      ansible.builtin.debug:
        msg: 'uid {{ getent_passwd[rheluser].1 }}'
        verbosity: 0
        
    - name: Mount NAS SMB volume
      ansible.posix.mount:
        src: //192.168.0.98/sync #TODO: use hostname
        path: /mnt/loop
        opts: "rw,vers=2.0,file_mode=0700,dir_mode=0770,uid={{ getent_passwd[rheluser].1}},gid={{ getent_passwd[rheluser].2}},username={{ smb_username }},password={{ smb_password }}"
        fstype: cifs
        state: mounted 
        boot: true
      become: true
      no_log: true #password shown in opts