# Takes a newly provisioned RHEL server and: 
# * Adds it to Ansible inventory (both permanent and temporary in-memory)
# * Makes sure Ansible can interact with that server (Python, SSH keys, etc.)
#
# Does not do any actual configuration of the host, which will be done via 
# provisioning scripts specific to its function.
# 

- name: Config new host in inventory
  hosts: localhost
  gather_facts: false
  vars:
    new_fqdn: "{{ new_hostname + '.' + new_domainname }}"
    ip_valid: "{{ new_ip | ansible.utils.ipaddr}}"
    exists_host: "{{ hostvars is contains( new_fqdn ) }}"
    hostitems: "{{ hostvars | dict2items }}"
    all_ips: []

  # roles:
  #   - role: robertdebock.bootstrap

  tasks:
    - name: Loop over inventory to find all IPs assigned
      ansible.builtin.set_fact:
        all_ips: "{{ all_ips + [item.value.dns_ip] }}"
      loop: "{{ hostitems }}"
      loop_control:
        label: "{{ item.key }}"
      when: item.value.dns_ip is defined

    - name: Debug list of all IPs
      ansible.builtin.debug:
        var: all_ips
        verbosity: 1

    - name: Determine if IP is available
      ansible.builtin.set_fact:
        ip_assigned: "{{ all_ips is contains(new_ip) }}"

    - name: Assert host can be created
      ansible.builtin.assert:
        that:
          - ip_valid != false
          - not exists_host
          - not ip_assigned

    # - name: Update list # TODO: Remove
    #   ansible.builtin.set_fact:
    #     new_foo: "{{ foo + ['qaz'] }}"    
        
    # - name: Add to inventory
    #   ansible.controller.host:
    #     name: "{{ new_fqdn }}"
    #     description: "For Testing"
    #     inventory: "Manual"
    #     state: present
    #     validate_certs: false
    #     controller_host: auto.loudwalrus.com ## To fix, needs to remotely call controller
    #     controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
    #     controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
    #     #controller_config_file: "~/tower_cli.cfg" 
    #     enabled: true
    #     variables:
    #       dns_ip: "{{ new_ip }}"
