- name: Config new host in inventory
  hosts: localhost
  vars:
    new_fqdn: "{{ new_hostname + '.' + new_domainname }}"
    valid_ip: "{{ new_ip | ansible.utils.ipaddr}}"
    exists_host: "{{ hostvars is contains( new_fqdn ) }}"
    hostitems: "{{ hostvars | dict2items }}"
    mylist: []

  # roles:
  #   - role: robertdebock.bootstrap

  tasks:
    - name: Dump exists
      ansible.builtin.debug:
        var: exists_host

    - name: Dump valid_ip`
      ansible.builtin.debug:
        var: valid_ip

    - name: Assert host can be created
      ansible.builtin.assert:
        that:
          - valid_ip != false
          - not exists_host

    - name: Dump list
      ansible.builtin.debug:
        var: hostitems

    - name: Loop over inventory
      ansible.builtin.set_fact:
        one_fact: foo
        mylist: "{{ mylist + [item.key] }}"
      loop: "{{ hostitems }}"

    - name: Print one
      ansible.builtin.debug:
        var: foo

    - name: Print final
      ansible.builtin.debug:
        var: mylist

    # - name: Update list # TODO: Remove
    #   ansible.builtin.set_fact:
    #     new_foo: "{{ foo + ['qaz'] }}"    
        
    # - name: Add to inventory
    #   ansible.controller.host:
    #     name: "{{ new_fqdn }}"
    #     description: "For Testing"
    #     inventory: "Manual"
    #     state: present
    #     validate_certs: false
    #     controller_host: auto.loudwalrus.com ## To fix, needs to remotely call controller
    #     controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
    #     controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
    #     #controller_config_file: "~/tower_cli.cfg" 
    #     enabled: true
    #     variables:
    #       dns_ip: "{{ new_ip }}"

