- name: Config new host in inventory
  hosts: localhost
  vars:
    new_fqdn: "{{ new_hostname + '.' + new_domainname }}"

  # roles:
  #   - role: robertdebock.bootstrap

  tasks:
    - name: Verify valid IP
      ansible.builtin.set_fact:
        var: valid_ip = "{{ new_ip | ansible.utils.ip }}" 
      failed_when: not valid_ip
      ignore_errors: true

    - name: Test select
      ansible.builtin.set_fact:
        var: exists_host = "{{ hostvars is contains( new_fqdn ) }}"
      failed_when: exists_host
 
    - name: Host vars 
      ansible.builtin.debug:
        var: hostvars

    - name: Host items
      ansible.builtin.set_fact:
        var: hostitems = "{{ hostvars| dict2items }}"

    - name: Test filter
      ansible.builtin.set_fact:
        var: dns_host_list = "{{ hostitems | subelements('dns_ip', skip_missing=True) }}"
      ignore_errors: true

    - name: Update list # TODO: Remove
      ansible.builtin.set_fact:
        new_foo: "{{ foo + ['qaz'] }}"    
        
    - name: Add to inventory
      ansible.controller.host:
        name: "{{ new_fqdn }}"
        description: "For Testing"
        inventory: "Manual"
        state: present
        validate_certs: false
        controller_host: auto.loudwalrus.com ## To fix, needs to remotely call controller
        controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
        controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
        #controller_config_file: "~/tower_cli.cfg" 
        enabled: true
        variables:
          dns_ip: "{{ new_ip }}"

