- name: Config new host in inventory
  hosts: localhost
  vars:
    new_fqdn: "{{ new_hostname + '.' + new_domainname }}"

  # roles:
  #   - role: robertdebock.bootstrap

  tasks:
    - name: Add to inventory
      ansible.controller.host:
        name: "{{ new_fqdn }}"
        description: "For Testing"
        inventory: "Manual"
        state: present
        validate_certs: false
        controller_host: auto.loudwalrus.com ## To fix, needs to remotely call controller
        controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
        controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
        #controller_config_file: "~/tower_cli.cfg" 
        enabled: true
        variables:
          dns_ip: "{{ new_ip }}"

