- name: Config new host in inventory
  hosts: localhost
  vars:
    new_fqdn: "{{ new_hostname + '.' + new_domainname }}"

  # roles:
  #   - role: robertdebock.bootstrap

  tasks:
    - name: Dump survey host
      ansible.builtin.debug:
        var: new_hostname

    - name: Dump survey domain
      ansible.builtin.debug:
        var: new_domainname

    - name: Dump survey ip
      ansible.builtin.debug:
        var: new_ip

    - name: Dump FQDN
      ansible.builtin.debug:
        var: new_fqdn

    - name: Add to inventory
      ansible.builtin.add_host:
        name: '{{ new_fqdn }}'
        groups: dummy
        foo: bar

- name: Initial kickstart
  hosts: new_fqdn

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: new_hostname
