- name: Config new host in inventory
  hosts: localhost
  vars:
    new_fqdn: "{{ new_hostname + '.' + new_domainname }}"
    ip_valid: "{{ new_ip | ansible.utils.ipaddr}}"
    exists_host: "{{ hostvars is contains( new_fqdn ) }}"
    hostitems: "{{ hostvars | dict2items }}"
    all_ips: []

  # roles:
  #   - role: robertdebock.bootstrap

  tasks:
    - name: Dump exists
      ansible.builtin.debug:
        var: exists_host

    - name: Dump ip_valid
      ansible.builtin.debug:
        var: ip_valid

    - name: Loop over inventory
      ansible.builtin.set_fact:
        all_ips: "{{ all_ips + [item.value.dns_ip] }}"
      loop: "{{ hostitems }}"
      when: item.value.dns_ip is defined

    - name: Determine if IP is available
      ansible.builtin.set_fact:
        ip_assigned: "{{ all_ips is contains(new_ip) }}"

    - name: Assert host can be created
      ansible.builtin.assert:
        that:
          - ip_valid != false
          - not exists_host
          - not ip_assigned

    - name: Dump list
      ansible.builtin.debug:
        var: hostitems

    - name: Print final
      ansible.builtin.debug:
        var: mylist

    # - name: Update list # TODO: Remove
    #   ansible.builtin.set_fact:
    #     new_foo: "{{ foo + ['qaz'] }}"    
        
    # - name: Add to inventory
    #   ansible.controller.host:
    #     name: "{{ new_fqdn }}"
    #     description: "For Testing"
    #     inventory: "Manual"
    #     state: present
    #     validate_certs: false
    #     controller_host: auto.loudwalrus.com ## To fix, needs to remotely call controller
    #     controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
    #     controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
    #     #controller_config_file: "~/tower_cli.cfg" 
    #     enabled: true
    #     variables:
    #       dns_ip: "{{ new_ip }}"

