# Because rebooting servers is (obviously) disruptive and needs to be controlled strictly
# this functionality has been moved into seperate playbooks.
#
# This playbook is specific to AAP controllers, as the error handling has to be different
# because the ansible controller rebooting obviously means that we can't monitor the reboot
# (at least in our non-HA AAP install config)

- name: Reboot if needed
  hosts: ansiblehosts
  strategy: linear
  serial: 1

  tasks:
    - name: Check to see if we need a reboot
      ansible.builtin.command: needs-restarting -r
      become: true
      register: needrestart_result
      changed_when: false

    - name: Reboot Server if Necessary
      ansible.builtin.reboot:
        msg: Ansible forcing reboot
        pre_reboot_delay: 0
        reboot_timeout: 0 #We can't stick around to wait for the reboot since we will be gone
      become: true
      when: needrestart_result.rc == 1
      failed_when: false # We basically have to ignore errors because we won't be around to check

# No sense doing async or  waiting for connectivity, since we are removing the ground beneath our feet
