- name: Reboot if needed
  hosts: ansiblehosts
  strategy: linear
  serial: 1

  tasks:
    - name: check to see if we need a reboot
      ansible.builtin.command: needs-restarting -r
      become: true
      register: needrestart_result

    - name: Reboot Server if Necessary
      ansible.builtin.reboot: 
        msg: Ansible forcing reboot
        pre_reboot_delay: 0
      become: true
      when: needrestart_result.rc == 1
      ignore_errors: true

# No sense doing async or  waiting for connectivity, since we are removing the ground beneath our feet