- hosts: all

  tasks:
  - name: apply security updates
    ansible.builtin.dnf:
      name: "*"
      state: latest
      update_only: true
      security: true
    become: true  
    register: dnf_taskout
