---
- name: Daily maintainence
  hosts: all
  gather_facts: false
  ignore_unreachable: true

  tasks:
    - name: Apply security updates
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
        security: true
      become: true
      register: dnf_taskout
