# Because rebooting servers is (obviously) disruptive and needs to be controlled strictly
# this functionality has been moved into seperate playbooks.

- name: Reboot if needed
  hosts: rhelserver
  strategy: linear
  serial: 1

  tasks:
    - name: Check to see if we need a reboot
      ansible.builtin.command: needs-restarting -r
      become: true
      register: needrestart_result
      changed_when: false

    - name: Reboot Server if Necessary
      ansible.builtin.reboot:
        msg: Ansible forcing reboot
        pre_reboot_delay: 0
      become: true
      when: needrestart_result.rc == 1
