# Master playbook for weekly tasks in the maintenance window.
# (Reboots are handled seperately)
---
- name: Pre Content Drift Prevention
  ansible.builtin.import_playbook: ../includes/pre_content.yml
  ignore_unreachable: true
- name: Configure Ansible Host
  ansible.builtin.import_playbook: ../provisioning/configure_ansiblehosts.yml
  ignore_unreachable: true
# TODO: Move provisioning/drift prevention here
- name: Update Content
  ansible.builtin.import_playbook: ../includes/content_update.yml
  ignore_unreachable: true

