# Experimenting with simple update playbooks
---
- name: Update controller first
  hosts: ansiblehosts
  vars:
    run: false
    reboot: false

  #Primarily just doing this as an example of a secondary credential
  tasks:
  - name: 'Register system using Red Hat Subscription Manager'
    community.general.redhat_subscription:
      state: present
      username: "{{ rhn_username }}"
      password: "{{ rhn_password }}"
      syspurpose:
        usage: "Production"
        role: "Red Hat Enterprise Server"
        service_level_agreement: "Self-Support"
    become: true

  #TODO: Verify the repos that I want (e.g. EPEL)

  - name: Add Standard content
    ansible.builtin.dnf:
      name: "{{ standard_packages }}"
      state: present #Will update in next step if necessary
    become: true
    register: dnf_ansible_taskout

  - name: Add Ansible content
    ansible.builtin.dnf:
      name: "{{ custom_content }}"
      enablerepo: ansible-automation-platform-2.4-for-rhel-8-x86_64-rpms
      state: present #Will update in next step if necessary
    become: true
    register: dnf_ansible_taskout

  - name: Update all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
      update_only: true
    become: true  
    register: dnf_update_taskout

  - name: Load passwd as database 
    ansible.builtin.getent:
      database: passwd

  - name: Log uid since mount task will be redacted
    ansible.builtin.debug:
      msg: 'uid {{ getent_passwd[rheluser].1 }}'
      
  - name: Mount NAS SMB volume
    ansible.posix.mount:
      src: //192.168.0.98/sync #TODO: use hostname
      path: /mnt/loop
      opts: "rw,vers=2.0,file_mode=0,dir_mode=0700,uid={{ getent_passwd[rheluser].1}} ,username={{ smb_username }},password={{ smb_password }}"
      fstype: cifs
      state: mounted 
      boot: true
    become: true
    no_log: false #password shown in opts



- name: Update all
  hosts: all
  vars:
    run: false
    reboot: false
  tasks:
  
  - name: 'Register system using Red Hat Subscription Manager'
    community.general.redhat_subscription:
      state: present
      username: "{{ rhn_username }}"
      password: "{{ rhn_password }}"
      syspurpose:
        usage: "Production"
        role: "Red Hat Enterprise Server"
        service_level_agreement: "Self-Support"
    become: true

  #TODO: Verify the repos that I want (e.g. EPEL)

  - name: Add Standard content
    ansible.builtin.dnf:
      name: "{{ standard_packages }}"
      state: present #Will update in next step if necessary
    become: true
    register: dnf_ansible_taskout

  - name: upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
      update_only: true
    become: true  
    register: dnf_taskout
    
  - name: check to see if we need a reboot
    command: needs-restarting -r
    become: true
    register: needrestart_result
    ignore_errors: yes

  - name: Reboot Server if Necessary
    command: shutdown -r now "Ansible Updates Triggered"
    become: true
    async: 30
    poll: 0
    when: needrestart_result.rc == 1 and "'ansiblehosts' not in group_names" | bool

  - name: Pausing to allow server to shutdown and terminate our SSH connection
    pause: seconds=30
    when: needrestart_result.rc == 1 and "'ansiblehosts' not in group_names" | bool

  - name: Wait for reboot to complete and SSH to become available
    local_action: wait_for host={{ inventory_hostname }} port=22
      state=started delay=30 timeout=600
    retries: 30    
    delay: 10
    when: needrestart_result.rc == 1 and "'ansiblehosts' not in group_names" | bool

- name: Reboot controller if needed
  hosts: ansiblehosts
  vars:
    run: false
    reboot: false
  tasks:
  - name: Reboot Server if Necessary
    command: shutdown -r now "Ansible Updates Triggered"
    become: true
    async: 30
    poll: 0
    when: needrestart_result.rc == 1

  - name: Reboot Server if Necessary
    command: shutdown -r now "Ansible Updates Triggered"
    become: true
    async: 30
    poll: 0
    when: needrestart_result.rc == 1

