# Drift prevention: standard configuration that should be in place on all
# RHEL servers to verify the system is registered, configured, and correct
# content is installed.
#
# Should not be disruptive.
#
# Requires RHN credentials

- name: Pre content
  hosts: rhelhosts
  strategy: free
  gather_facts: true # We gather facts because many templates that call this will cache facts
  
  roles:
    - role:  rhel-system-roles.rhc 
      become: yes
      vars:
        rhc_insights:
          state: present
        rhc_auth:
          login:
            username: "{{ rhn_username }}"
            password: "{{ rhn_password }}"

    - role: robertdebock.core_dependencies
      become: yes
   
# TODO: handler for syspurpose


  tasks:
    - name: Add Standard content
      ansible.builtin.dnf:
        name: "{{ standard_packages }}"
        state: present #Will update in next step if necessary
      become: true

    - name: Install RHEL web console
      ansible.builtin.include_role:
        name: rhel-system-roles.cockpit
      vars:
        cockpit_packages: default
        cockpit_manage_selinux: true
        cockpit_manage_firewall: true

    #TODO: metrics

    #TODO: network config

