# Drift prevention: standard configuration that should be in place on all
# RHEL servers to verify the system is registered, configured, and correct
# content is installed.
#
# Should not be disruptive.
#
# Requires RHN credentials

- name: Pre content
  hosts: rhelhosts
  strategy: free
  ignore_unreachable: true
  gather_facts: true # We gather facts because many templates that call this will cache facts
  
  roles:
    - role: redhat.rhel_system_roles.rhc 
      become: yes
      vars:
        rhc_insights:
          state: present
        rhc_auth:
          login:
            username: "{{ rhn_username }}"
            password: "{{ rhn_password }}"

    - role: robertdebock.core_dependencies
      become: yes
   
    - role: redhat.rhel_system_roles.cockpit
      become: true
      vars:
        cockpit_packages: default
        cockpit_manage_selinux: true
        cockpit_manage_firewall: true

   # TODO: handler for syspurpose

  tasks:
    - name: Add Standard content
      become: true
      ansible.builtin.dnf:
        name: "{{ standard_packages }}"
        state: present #Will update in next step if necessary



    #TODO: metrics

    #TODO: network config

