# Drift prevention: standard configuration that should be in place on all
# RHEL servers to verify the system is registered, configured, and correct
# content is installed.
#
# Should not be disruptive.
#
# Requires RHN credentials

- name: Pre content
  hosts: rhelhosts
  strategy: free
  gather_facts: true # We gather facts because many templates that call this will cache facts
  
  pre_tasks:
    - name: 'Register system using Red Hat Subscription Manager'
      community.general.redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        syspurpose:
          usage: "Production"
          role: "Red Hat Enterprise Server"
          service_level_agreement: "Self-Support"
      become: true

  roles:
    - role: robertdebock.core_dependencies
      become: yes

  tasks:
    - name: Add Standard content
      ansible.builtin.dnf:
        name: "{{ standard_packages }}"
        state: present #Will update in next step if necessary
      become: true
      notify: Restart cockpit

    #TODO: network config

  handlers:
    - name: Restart cockpit
      ansible.builtin.systemd_service:
        state: restarted
        name: cockpit

