---
- name: Update image mode hosts in test lifecycle
  hosts: imagemode_test_hosts
  remote_user: ogren
  tasks:

# Ansible module doesn't yet support soft reboot, so I will use raw command 
#    - name: Stage new image
#      community.general.bootc_manage:
#        state: latest
   - name: Stage new image
     ansible.builtin.command:
       cmd: "bootc status"
       register: bootc_status
   - name: Show output
     ansible.builtin.debug:
       var: bootc_status
