- hosts: all
  roles:
    - rhsm
  tasks:
  - name: 'Register system using Red Hat Subscription Manager'
    redhat_subscription:
      state: present
      username: "{{ uid_username) }}"
      password: "{{ uid_password }}"
    become: true
  - name: apply security updates
    ansible.builtin.dnf:
      name: "*"
      state: latest
      update_only: true
      security: true
    become: true  
    register: dnf_taskout
