- name: Add host to inventory
  hosts: auto.loudwalrus.com ## To fix, needs to run on DNS
  vars: 
     groupinfo: "{{ groups }}"
     
  tasks:

  - name: Get group info
    ansible.builtin.debug:
      var: group_names
    ignore_errors: true
      
  - name: Get groups 
    ansible.builtin.debug:
      var: groups['dummy']
      
  - name: Host vars 
    ansible.builtin.debug:
      var: foo
      
  - name: Add group
    ansible.controller.group:
      name: dummy
      description: "For Testing"
      inventory: "Manual"
      state: present
      validate_certs: false
      controller_host: localhost ## To fix, needs to remotely call controller
      controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
      controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
      #controller_config_file: "~/tower_cli.cfg"
      variables:
        foo: 
          - bar 
          - baz