- name: Add host to inventory
  hosts: auto.loudwalrus.com
  tasks:

  - name: Add group
    awx.awx.group:
      name: dummy
      description: "For Testing"
      inventory: "Manual"
      state: present
      validate_certs: false
      controller_host: localhost
      controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
      controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
      #controller_config_file: "~/tower_cli.cfg"
      variables:
        foo: 
          - bar 
          - baz