- name: Copy master SSH keys to NAS
  hosts: auto.loudwalrus.com
  tasks:

  - name: Load passwd as database 
    ansible.builtin.getent:
      database: passwd

  - name: Log uid since mount task will be redacted
    ansible.builtin.debug:
      msg: 'uid {{ getent_passwd[rheluser] }}'
      
  - name: Mount NAS SMB volume
    ansible.posix.mount:
      src: //192.168.0.98/sync #TODO: use hostname
      path: /mnt/loop
      opts: "rw,vers=2.0,file_mode=0700,dir_mode=0770,uid={{ getent_passwd[rheluser].1}},gid={{ getent_passwd[rheluser].2}},username={{ smb_username }},password={{ smb_password }}"
      fstype: cifs
      state: present
      boot: true
    become: true
    no_log: false #password shown in opts

  - name: test 1 (pass?)
    ansible.builtin.copy:
      src:  "/home/ogren/.ssh/id_ecdsa.pub"
      dest:  "/home/ogren/foo"
      #backup: true
      remote_src: true
      #unsafe_writes: true
    ignore_errors: true

  - name: Copy public key (root?)
    ansible.builtin.copy:
      src:  "/home/ogren/.ssh/id_ecdsa.pub"
      dest:  "/mnt/loop/ansible/ssh_keys/id_ecdsa.pub"
      #backup: true
      remote_src: true
      #unsafe_writes: true
    become: true
    ignore_errors: true
      
  - name: Copy secret key (remote?)
    ansible.builtin.copy:
      src:  "/home/{{ rheluser  }}/.ssh/id_ecdsa"
      dest:  "/mnt/loop/ansible/ssh_keys/id_ecdsa"
      #backup: true
      remote_src: true
      unsafe_writes: true
    ignore_errors: true



  
