- name: Copy master SSH keys to NAS
  hosts: auto.loudwalrus.com
  tasks:

  - name: Load passwd as database 
    ansible.builtin.getent:
      database: passwd

  - name: Log uid since mount task will be redacted
    ansible.builtin.debug:
      msg: 'uid {{ getent_passwd[rheluser].1 }}'
      
  - name: Mount NAS SMB volume
    ansible.posix.mount:
      src: //192.168.0.98/sync #TODO: use hostname
      path: /mnt/loop
      opts: "rw,vers=2.0,file_mode=0,dir_mode=0700,uid={{ getent_passwd[rheluser].1}},username={{ smb_username }},password={{ smb_password }}"
      fstype: cifs
      state: present
      boot: true
    become: true
    no_log: true #password shown in opts

  - name: Copy public key
    ansible.builtin.copy:
      src:  "/home/{{ rheluser  }}/.ssh/id_ecdsa.pub"
      dest:  /mnt/loop/ansible/ssh_keys/
      backup: true
      remote_src: true
      unsafe_writes: true
      
  - name: Copy secret key
    ansible.builtin.copy:
      src:  "/home/{{ rheluser  }}/.ssh/id_ecdsa"
      dest:  /mnt/loop/ansible/ssh_keys/
      backup: true
      remote_src: true
      unsafe_writes: true



  
