---
- name: WIP to configure DNS
  hosts: all #We need to run as all so that all of hostvars is populated
  gather_facts: false
  ignore_unreachable: true
  strategy: free
  vars:
    test_var: Fred
#    dns_zones: "{{ lookup('ansible.builtin.template', '../../templates/dns_zones.j2') | from_yaml }}"
    dns_list: "{{ hostvars | dict2items }}"

#  pre_tasks:
#    - name:
#

  pre_tasks:
    - name: Dump hostvars
      ansible.builtin.debug:
        var: dns_list
      when: inventory_hostname in groups["dnshosts"]

    - name: Show templating
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.template', '../../templates/dns_zones.j2') | from_yaml }}"
      when: inventory_hostname in groups["dnshosts"]

  roles:
    - role: robertdebock.dns
      become: true
      when: inventory_hostname in groups["dnshosts"]
      dns_allow_transfer:
      - none
        "127.0.0.1"
      dns_zones: "{{ lookup('ansible.builtin.template', '../../templates/dns_zones.j2') | from_yaml }}"
 