- name: WIP to mount loop
  hosts: auto.loudwalrus.com

  tasks:
  - name: Install package for SMB mount
    ansible.builtin.dnf:
      name: cifs-utils
      state: latest
    become: true
    register: dnf_taskout

  ## TODO verify DNS mount

  - name: Mount ephemeral SMB volume
    ansible.posix.mount:
      src: //192.168.0.98/sync #TODO: use hostname
      path: /mnt/loop
      opts: "rw,vers=3,file_mode=0600,dir_mode=0700,username={{ uid_username }},password={{ uid_password }}"
      fstype: cifs
      state: mounted
      backup: true #TODO: remove
      boot: true
