## Play expected to run as root
- name: WIP to mount loop
  hosts: auto.loudwalrus.com
  vars:
    run: false
    reboot: false

  tasks:
  - name: Install package for SMB mount
    ansible.builtin.dnf:
      name: cifs-utils
      state: latest
    register: dnf_taskout

  ## TODO verify DNS mount

  - name: Load passwd as database 
    ansible.builtin.getent:
      database: passwd

  - name: verify uid
    ansible.builtin.debug:
      msg: 'uid {{ getent_passwd["ogren"].1 }}'
      

  - name: Mount ephemeral SMB volume
    ansible.posix.mount:
      src: //192.168.0.98/sync #TODO: use hostname
      path: /mnt/loop
      opts: "rw,vers=2.0,file_mode=0,dir_mode=0700,username={{ uid_username }},password={{ uid_password }}"
      fstype: cifs
      state: mounted
      backup: true #TODO: remove
      boot: true
