# Test playbook for changing DNS resolution
- name: Test network config
  hosts: boba.loudwalrus.com
  gather_facts: true
  vars:
    network_provider: nm
    network_connections:
      - name: eth0
        type: ethernet
        interface_name: eth0
        ip:
          dhcp4: true
          dns:
            - 192.168.0.66
          dns_search:
            - loudwalrus.com
    network_state:
      - name: eth0
        type: ethernet
        ipv4: 
          enabled: true
          dhcp: true
  roles:
    - name: redhat.rhel_system_roles.network
      become: true